// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package reservepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReserveServiceClient is the client API for ReserveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReserveServiceClient interface {
	// reserve time is not flexible and fixed at 1 hour
	ReserveOneHour(ctx context.Context, in *ReserveOneHourRequest, opts ...grpc.CallOption) (*ReserveOneHourResponse, error)
	// FindAllUserReserves only returns reserves which are not exceeded
	FindAllUserReserves(ctx context.Context, in *FindAllUserReservesRequest, opts ...grpc.CallOption) (*FindAllUserReservesResponse, error)
	// FindAllConsultantReserves only returns reserves which are not exceeded
	FindAllConsultantReserves(ctx context.Context, in *FindAllConsultantReservesRequest, opts ...grpc.CallOption) (*FindAllConsultantReservesResponse, error)
}

type reserveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReserveServiceClient(cc grpc.ClientConnInterface) ReserveServiceClient {
	return &reserveServiceClient{cc}
}

func (c *reserveServiceClient) ReserveOneHour(ctx context.Context, in *ReserveOneHourRequest, opts ...grpc.CallOption) (*ReserveOneHourResponse, error) {
	out := new(ReserveOneHourResponse)
	err := c.cc.Invoke(ctx, "/reserve.ReserveService/ReserveOneHour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveServiceClient) FindAllUserReserves(ctx context.Context, in *FindAllUserReservesRequest, opts ...grpc.CallOption) (*FindAllUserReservesResponse, error) {
	out := new(FindAllUserReservesResponse)
	err := c.cc.Invoke(ctx, "/reserve.ReserveService/FindAllUserReserves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveServiceClient) FindAllConsultantReserves(ctx context.Context, in *FindAllConsultantReservesRequest, opts ...grpc.CallOption) (*FindAllConsultantReservesResponse, error) {
	out := new(FindAllConsultantReservesResponse)
	err := c.cc.Invoke(ctx, "/reserve.ReserveService/FindAllConsultantReserves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReserveServiceServer is the server API for ReserveService service.
// All implementations must embed UnimplementedReserveServiceServer
// for forward compatibility
type ReserveServiceServer interface {
	// reserve time is not flexible and fixed at 1 hour
	ReserveOneHour(context.Context, *ReserveOneHourRequest) (*ReserveOneHourResponse, error)
	// FindAllUserReserves only returns reserves which are not exceeded
	FindAllUserReserves(context.Context, *FindAllUserReservesRequest) (*FindAllUserReservesResponse, error)
	// FindAllConsultantReserves only returns reserves which are not exceeded
	FindAllConsultantReserves(context.Context, *FindAllConsultantReservesRequest) (*FindAllConsultantReservesResponse, error)
	mustEmbedUnimplementedReserveServiceServer()
}

// UnimplementedReserveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReserveServiceServer struct {
}

func (UnimplementedReserveServiceServer) ReserveOneHour(context.Context, *ReserveOneHourRequest) (*ReserveOneHourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveOneHour not implemented")
}
func (UnimplementedReserveServiceServer) FindAllUserReserves(context.Context, *FindAllUserReservesRequest) (*FindAllUserReservesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllUserReserves not implemented")
}
func (UnimplementedReserveServiceServer) FindAllConsultantReserves(context.Context, *FindAllConsultantReservesRequest) (*FindAllConsultantReservesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllConsultantReserves not implemented")
}
func (UnimplementedReserveServiceServer) mustEmbedUnimplementedReserveServiceServer() {}

// UnsafeReserveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReserveServiceServer will
// result in compilation errors.
type UnsafeReserveServiceServer interface {
	mustEmbedUnimplementedReserveServiceServer()
}

func RegisterReserveServiceServer(s grpc.ServiceRegistrar, srv ReserveServiceServer) {
	s.RegisterService(&ReserveService_ServiceDesc, srv)
}

func _ReserveService_ReserveOneHour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveOneHourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).ReserveOneHour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reserve.ReserveService/ReserveOneHour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).ReserveOneHour(ctx, req.(*ReserveOneHourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReserveService_FindAllUserReserves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllUserReservesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).FindAllUserReserves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reserve.ReserveService/FindAllUserReserves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).FindAllUserReserves(ctx, req.(*FindAllUserReservesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReserveService_FindAllConsultantReserves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllConsultantReservesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).FindAllConsultantReserves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reserve.ReserveService/FindAllConsultantReserves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).FindAllConsultantReserves(ctx, req.(*FindAllConsultantReservesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReserveService_ServiceDesc is the grpc.ServiceDesc for ReserveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReserveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reserve.ReserveService",
	HandlerType: (*ReserveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveOneHour",
			Handler:    _ReserveService_ReserveOneHour_Handler,
		},
		{
			MethodName: "FindAllUserReserves",
			Handler:    _ReserveService_FindAllUserReserves_Handler,
		},
		{
			MethodName: "FindAllConsultantReserves",
			Handler:    _ReserveService_FindAllConsultantReserves_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/pbs/reservepb/reserve.proto",
}
