// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: src/pbs/schudulepb/schudule.proto

package schudulepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schudule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	StartHour    int32                  `protobuf:"varint,3,opt,name=start_hour,json=startHour,proto3" json:"start_hour,omitempty"`
	FinishHour   int32                  `protobuf:"varint,4,opt,name=finish_hour,json=finishHour,proto3" json:"finish_hour,omitempty"`
	ConsultantId int32                  `protobuf:"varint,5,opt,name=consultant_id,json=consultantId,proto3" json:"consultant_id,omitempty"`
}

func (x *Schudule) Reset() {
	*x = Schudule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schudule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schudule) ProtoMessage() {}

func (x *Schudule) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schudule.ProtoReflect.Descriptor instead.
func (*Schudule) Descriptor() ([]byte, []int) {
	return file_src_pbs_schudulepb_schudule_proto_rawDescGZIP(), []int{0}
}

func (x *Schudule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Schudule) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Schudule) GetStartHour() int32 {
	if x != nil {
		return x.StartHour
	}
	return 0
}

func (x *Schudule) GetFinishHour() int32 {
	if x != nil {
		return x.FinishHour
	}
	return 0
}

func (x *Schudule) GetConsultantId() int32 {
	if x != nil {
		return x.ConsultantId
	}
	return 0
}

type CreateSchuduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schudule *Schudule `protobuf:"bytes,1,opt,name=schudule,proto3" json:"schudule,omitempty"`
}

func (x *CreateSchuduleRequest) Reset() {
	*x = CreateSchuduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSchuduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchuduleRequest) ProtoMessage() {}

func (x *CreateSchuduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchuduleRequest.ProtoReflect.Descriptor instead.
func (*CreateSchuduleRequest) Descriptor() ([]byte, []int) {
	return file_src_pbs_schudulepb_schudule_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSchuduleRequest) GetSchudule() *Schudule {
	if x != nil {
		return x.Schudule
	}
	return nil
}

type CreateSchuduleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schudule *Schudule `protobuf:"bytes,1,opt,name=schudule,proto3" json:"schudule,omitempty"`
}

func (x *CreateSchuduleResponse) Reset() {
	*x = CreateSchuduleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSchuduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchuduleResponse) ProtoMessage() {}

func (x *CreateSchuduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchuduleResponse.ProtoReflect.Descriptor instead.
func (*CreateSchuduleResponse) Descriptor() ([]byte, []int) {
	return file_src_pbs_schudulepb_schudule_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSchuduleResponse) GetSchudule() *Schudule {
	if x != nil {
		return x.Schudule
	}
	return nil
}

type FindAllOpenSchudulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllOpenSchudulesRequest) Reset() {
	*x = FindAllOpenSchudulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllOpenSchudulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOpenSchudulesRequest) ProtoMessage() {}

func (x *FindAllOpenSchudulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOpenSchudulesRequest.ProtoReflect.Descriptor instead.
func (*FindAllOpenSchudulesRequest) Descriptor() ([]byte, []int) {
	return file_src_pbs_schudulepb_schudule_proto_rawDescGZIP(), []int{3}
}

type FindAllOpenSchudulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schudules []*Schudule `protobuf:"bytes,1,rep,name=schudules,proto3" json:"schudules,omitempty"`
}

func (x *FindAllOpenSchudulesResponse) Reset() {
	*x = FindAllOpenSchudulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllOpenSchudulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOpenSchudulesResponse) ProtoMessage() {}

func (x *FindAllOpenSchudulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOpenSchudulesResponse.ProtoReflect.Descriptor instead.
func (*FindAllOpenSchudulesResponse) Descriptor() ([]byte, []int) {
	return file_src_pbs_schudulepb_schudule_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllOpenSchudulesResponse) GetSchudules() []*Schudule {
	if x != nil {
		return x.Schudules
	}
	return nil
}

type FindConsultantOpenSchudulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsultantId int32 `protobuf:"varint,1,opt,name=consultant_id,json=consultantId,proto3" json:"consultant_id,omitempty"`
}

func (x *FindConsultantOpenSchudulesRequest) Reset() {
	*x = FindConsultantOpenSchudulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindConsultantOpenSchudulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindConsultantOpenSchudulesRequest) ProtoMessage() {}

func (x *FindConsultantOpenSchudulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindConsultantOpenSchudulesRequest.ProtoReflect.Descriptor instead.
func (*FindConsultantOpenSchudulesRequest) Descriptor() ([]byte, []int) {
	return file_src_pbs_schudulepb_schudule_proto_rawDescGZIP(), []int{5}
}

func (x *FindConsultantOpenSchudulesRequest) GetConsultantId() int32 {
	if x != nil {
		return x.ConsultantId
	}
	return 0
}

type FindConsultantOpenSchudulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schudules []*Schudule `protobuf:"bytes,1,rep,name=schudules,proto3" json:"schudules,omitempty"`
}

func (x *FindConsultantOpenSchudulesResponse) Reset() {
	*x = FindConsultantOpenSchudulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindConsultantOpenSchudulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindConsultantOpenSchudulesResponse) ProtoMessage() {}

func (x *FindConsultantOpenSchudulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_schudulepb_schudule_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindConsultantOpenSchudulesResponse.ProtoReflect.Descriptor instead.
func (*FindConsultantOpenSchudulesResponse) Descriptor() ([]byte, []int) {
	return file_src_pbs_schudulepb_schudule_proto_rawDescGZIP(), []int{6}
}

func (x *FindConsultantOpenSchudulesResponse) GetSchudules() []*Schudule {
	if x != nil {
		return x.Schudules
	}
	return nil
}

var File_src_pbs_schudulepb_schudule_proto protoreflect.FileDescriptor

var file_src_pbs_schudulepb_schudule_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75,
	0x6c, 0x65, 0x70, 0x62, 0x2f, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x1a, 0x17, 0x73,
	0x72, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x01, 0x0a, 0x08, 0x53, 0x63, 0x68, 0x75, 0x64,
	0x75, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x75,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x48, 0x6f,
	0x75, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x68, 0x6f, 0x75,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x48,
	0x6f, 0x75, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x53,
	0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x08, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c,
	0x65, 0x22, 0x48, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x75, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x73,
	0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x08, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x1c, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x63,
	0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x09, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x22,
	0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x4f, 0x70,
	0x65, 0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x23, 0x46, 0x69, 0x6e, 0x64, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x63, 0x68,
	0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x09, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x63, 0x68,
	0x75, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x32, 0xcf, 0x02, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63,
	0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75,
	0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x14, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x63, 0x68,
	0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4f, 0x70, 0x65,
	0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x7c, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x12, 0x2c, 0x2e, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x53, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2d, 0x2e, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x53,
	0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x1a, 0x5a, 0x0b, 0x2f, 0x73, 0x63, 0x68, 0x75, 0x64, 0x75, 0x6c, 0x65, 0x70,
	0x62, 0xaa, 0x02, 0x0a, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_pbs_schudulepb_schudule_proto_rawDescOnce sync.Once
	file_src_pbs_schudulepb_schudule_proto_rawDescData = file_src_pbs_schudulepb_schudule_proto_rawDesc
)

func file_src_pbs_schudulepb_schudule_proto_rawDescGZIP() []byte {
	file_src_pbs_schudulepb_schudule_proto_rawDescOnce.Do(func() {
		file_src_pbs_schudulepb_schudule_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_pbs_schudulepb_schudule_proto_rawDescData)
	})
	return file_src_pbs_schudulepb_schudule_proto_rawDescData
}

var file_src_pbs_schudulepb_schudule_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_src_pbs_schudulepb_schudule_proto_goTypes = []interface{}{
	(*Schudule)(nil),                            // 0: schudule.Schudule
	(*CreateSchuduleRequest)(nil),               // 1: schudule.CreateSchuduleRequest
	(*CreateSchuduleResponse)(nil),              // 2: schudule.CreateSchuduleResponse
	(*FindAllOpenSchudulesRequest)(nil),         // 3: schudule.FindAllOpenSchudulesRequest
	(*FindAllOpenSchudulesResponse)(nil),        // 4: schudule.FindAllOpenSchudulesResponse
	(*FindConsultantOpenSchudulesRequest)(nil),  // 5: schudule.FindConsultantOpenSchudulesRequest
	(*FindConsultantOpenSchudulesResponse)(nil), // 6: schudule.FindConsultantOpenSchudulesResponse
	(*timestamppb.Timestamp)(nil),               // 7: google.protobuf.Timestamp
}
var file_src_pbs_schudulepb_schudule_proto_depIdxs = []int32{
	7, // 0: schudule.Schudule.date:type_name -> google.protobuf.Timestamp
	0, // 1: schudule.CreateSchuduleRequest.schudule:type_name -> schudule.Schudule
	0, // 2: schudule.CreateSchuduleResponse.schudule:type_name -> schudule.Schudule
	0, // 3: schudule.FindAllOpenSchudulesResponse.schudules:type_name -> schudule.Schudule
	0, // 4: schudule.FindConsultantOpenSchudulesResponse.schudules:type_name -> schudule.Schudule
	1, // 5: schudule.SchuduleService.CreateSchudule:input_type -> schudule.CreateSchuduleRequest
	3, // 6: schudule.SchuduleService.FindAllOpenSchudules:input_type -> schudule.FindAllOpenSchudulesRequest
	5, // 7: schudule.SchuduleService.FindConsultantOpenSchudules:input_type -> schudule.FindConsultantOpenSchudulesRequest
	2, // 8: schudule.SchuduleService.CreateSchudule:output_type -> schudule.CreateSchuduleResponse
	4, // 9: schudule.SchuduleService.FindAllOpenSchudules:output_type -> schudule.FindAllOpenSchudulesResponse
	6, // 10: schudule.SchuduleService.FindConsultantOpenSchudules:output_type -> schudule.FindConsultantOpenSchudulesResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_src_pbs_schudulepb_schudule_proto_init() }
func file_src_pbs_schudulepb_schudule_proto_init() {
	if File_src_pbs_schudulepb_schudule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_pbs_schudulepb_schudule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schudule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_schudulepb_schudule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSchuduleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_schudulepb_schudule_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSchuduleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_schudulepb_schudule_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllOpenSchudulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_schudulepb_schudule_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllOpenSchudulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_schudulepb_schudule_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindConsultantOpenSchudulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_schudulepb_schudule_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindConsultantOpenSchudulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_pbs_schudulepb_schudule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_pbs_schudulepb_schudule_proto_goTypes,
		DependencyIndexes: file_src_pbs_schudulepb_schudule_proto_depIdxs,
		MessageInfos:      file_src_pbs_schudulepb_schudule_proto_msgTypes,
	}.Build()
	File_src_pbs_schudulepb_schudule_proto = out.File
	file_src_pbs_schudulepb_schudule_proto_rawDesc = nil
	file_src_pbs_schudulepb_schudule_proto_goTypes = nil
	file_src_pbs_schudulepb_schudule_proto_depIdxs = nil
}
