// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package reportpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReportServiceClient interface {
	// create new record perhaps by sensor or a person
	// Errors: Internal
	CreateReport(ctx context.Context, in *SensorReportRequest, opts ...grpc.CallOption) (*SensorReportResponse, error)
	// get report information by id
	GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error)
	// get all uncompleted reports by server streaming technique
	GetUnCompletedReports(ctx context.Context, in *GetUnCompletedReportsRequest, opts ...grpc.CallOption) (*GetUnCompletedReportsResponse, error)
	// get all logs which are relevant to specified report with "id"
	GetReportLogs(ctx context.Context, in *GetReportLogRequest, opts ...grpc.CallOption) (*GetReportLogResponse, error)
	// Errors: Internal
	GetAllLogs(ctx context.Context, in *GetAllLogsRequest, opts ...grpc.CallOption) (*GetAllLogsResponse, error)
	// Errors: NotFound, Internal
	DoReportCommand(ctx context.Context, in *DoReportCommandRequest, opts ...grpc.CallOption) (*DoReportCommandResponse, error)
	GetSensorReports(ctx context.Context, in *GetSensorReportsRequest, opts ...grpc.CallOption) (*GetSensorReportsResponse, error)
	GetSensorsReportsCount(ctx context.Context, in *GetSensorsReportsCountRequest, opts ...grpc.CallOption) (*GetSensorsReportsCountResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) CreateReport(ctx context.Context, in *SensorReportRequest, opts ...grpc.CallOption) (*SensorReportResponse, error) {
	out := new(SensorReportResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/CreateReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error) {
	out := new(GetReportResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/GetReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetUnCompletedReports(ctx context.Context, in *GetUnCompletedReportsRequest, opts ...grpc.CallOption) (*GetUnCompletedReportsResponse, error) {
	out := new(GetUnCompletedReportsResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/GetUnCompletedReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetReportLogs(ctx context.Context, in *GetReportLogRequest, opts ...grpc.CallOption) (*GetReportLogResponse, error) {
	out := new(GetReportLogResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/GetReportLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetAllLogs(ctx context.Context, in *GetAllLogsRequest, opts ...grpc.CallOption) (*GetAllLogsResponse, error) {
	out := new(GetAllLogsResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/GetAllLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) DoReportCommand(ctx context.Context, in *DoReportCommandRequest, opts ...grpc.CallOption) (*DoReportCommandResponse, error) {
	out := new(DoReportCommandResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/DoReportCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetSensorReports(ctx context.Context, in *GetSensorReportsRequest, opts ...grpc.CallOption) (*GetSensorReportsResponse, error) {
	out := new(GetSensorReportsResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/GetSensorReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) GetSensorsReportsCount(ctx context.Context, in *GetSensorsReportsCountRequest, opts ...grpc.CallOption) (*GetSensorsReportsCountResponse, error) {
	out := new(GetSensorsReportsCountResponse)
	err := c.cc.Invoke(ctx, "/report.ReportService/GetSensorsReportsCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility
type ReportServiceServer interface {
	// create new record perhaps by sensor or a person
	// Errors: Internal
	CreateReport(context.Context, *SensorReportRequest) (*SensorReportResponse, error)
	// get report information by id
	GetReport(context.Context, *GetReportRequest) (*GetReportResponse, error)
	// get all uncompleted reports by server streaming technique
	GetUnCompletedReports(context.Context, *GetUnCompletedReportsRequest) (*GetUnCompletedReportsResponse, error)
	// get all logs which are relevant to specified report with "id"
	GetReportLogs(context.Context, *GetReportLogRequest) (*GetReportLogResponse, error)
	// Errors: Internal
	GetAllLogs(context.Context, *GetAllLogsRequest) (*GetAllLogsResponse, error)
	// Errors: NotFound, Internal
	DoReportCommand(context.Context, *DoReportCommandRequest) (*DoReportCommandResponse, error)
	GetSensorReports(context.Context, *GetSensorReportsRequest) (*GetSensorReportsResponse, error)
	GetSensorsReportsCount(context.Context, *GetSensorsReportsCountRequest) (*GetSensorsReportsCountResponse, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (UnimplementedReportServiceServer) CreateReport(context.Context, *SensorReportRequest) (*SensorReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReport not implemented")
}
func (UnimplementedReportServiceServer) GetReport(context.Context, *GetReportRequest) (*GetReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReport not implemented")
}
func (UnimplementedReportServiceServer) GetUnCompletedReports(context.Context, *GetUnCompletedReportsRequest) (*GetUnCompletedReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnCompletedReports not implemented")
}
func (UnimplementedReportServiceServer) GetReportLogs(context.Context, *GetReportLogRequest) (*GetReportLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportLogs not implemented")
}
func (UnimplementedReportServiceServer) GetAllLogs(context.Context, *GetAllLogsRequest) (*GetAllLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllLogs not implemented")
}
func (UnimplementedReportServiceServer) DoReportCommand(context.Context, *DoReportCommandRequest) (*DoReportCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoReportCommand not implemented")
}
func (UnimplementedReportServiceServer) GetSensorReports(context.Context, *GetSensorReportsRequest) (*GetSensorReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorReports not implemented")
}
func (UnimplementedReportServiceServer) GetSensorsReportsCount(context.Context, *GetSensorsReportsCountRequest) (*GetSensorsReportsCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorsReportsCount not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/CreateReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).CreateReport(ctx, req.(*SensorReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/GetReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetReport(ctx, req.(*GetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetUnCompletedReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnCompletedReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetUnCompletedReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/GetUnCompletedReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetUnCompletedReports(ctx, req.(*GetUnCompletedReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetReportLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetReportLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/GetReportLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetReportLogs(ctx, req.(*GetReportLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetAllLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetAllLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/GetAllLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetAllLogs(ctx, req.(*GetAllLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_DoReportCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoReportCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).DoReportCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/DoReportCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).DoReportCommand(ctx, req.(*DoReportCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetSensorReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSensorReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetSensorReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/GetSensorReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetSensorReports(ctx, req.(*GetSensorReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_GetSensorsReportsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSensorsReportsCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GetSensorsReportsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/GetSensorsReportsCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GetSensorsReportsCount(ctx, req.(*GetSensorsReportsCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "report.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReport",
			Handler:    _ReportService_CreateReport_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _ReportService_GetReport_Handler,
		},
		{
			MethodName: "GetUnCompletedReports",
			Handler:    _ReportService_GetUnCompletedReports_Handler,
		},
		{
			MethodName: "GetReportLogs",
			Handler:    _ReportService_GetReportLogs_Handler,
		},
		{
			MethodName: "GetAllLogs",
			Handler:    _ReportService_GetAllLogs_Handler,
		},
		{
			MethodName: "DoReportCommand",
			Handler:    _ReportService_DoReportCommand_Handler,
		},
		{
			MethodName: "GetSensorReports",
			Handler:    _ReportService_GetSensorReports_Handler,
		},
		{
			MethodName: "GetSensorsReportsCount",
			Handler:    _ReportService_GetSensorsReportsCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/pbs/reportpb/report.proto",
}
