// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: src/pbs/consultantpb/consultant.proto

package consultantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Consultant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone       string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Family      string `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Consultant) Reset() {
	*x = Consultant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consultant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consultant) ProtoMessage() {}

func (x *Consultant) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consultant.ProtoReflect.Descriptor instead.
func (*Consultant) Descriptor() ([]byte, []int) {
	return file_src_pbs_consultantpb_consultant_proto_rawDescGZIP(), []int{0}
}

func (x *Consultant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Consultant) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Consultant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Consultant) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *Consultant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type FindConsultantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsultantId int32 `protobuf:"varint,1,opt,name=consultant_id,json=consultantId,proto3" json:"consultant_id,omitempty"`
}

func (x *FindConsultantRequest) Reset() {
	*x = FindConsultantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindConsultantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindConsultantRequest) ProtoMessage() {}

func (x *FindConsultantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindConsultantRequest.ProtoReflect.Descriptor instead.
func (*FindConsultantRequest) Descriptor() ([]byte, []int) {
	return file_src_pbs_consultantpb_consultant_proto_rawDescGZIP(), []int{1}
}

func (x *FindConsultantRequest) GetConsultantId() int32 {
	if x != nil {
		return x.ConsultantId
	}
	return 0
}

type FindConsultantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consultant *Consultant `protobuf:"bytes,1,opt,name=consultant,proto3" json:"consultant,omitempty"`
}

func (x *FindConsultantResponse) Reset() {
	*x = FindConsultantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindConsultantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindConsultantResponse) ProtoMessage() {}

func (x *FindConsultantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindConsultantResponse.ProtoReflect.Descriptor instead.
func (*FindConsultantResponse) Descriptor() ([]byte, []int) {
	return file_src_pbs_consultantpb_consultant_proto_rawDescGZIP(), []int{2}
}

func (x *FindConsultantResponse) GetConsultant() *Consultant {
	if x != nil {
		return x.Consultant
	}
	return nil
}

type FindAllConsultantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllConsultantsRequest) Reset() {
	*x = FindAllConsultantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllConsultantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllConsultantsRequest) ProtoMessage() {}

func (x *FindAllConsultantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllConsultantsRequest.ProtoReflect.Descriptor instead.
func (*FindAllConsultantsRequest) Descriptor() ([]byte, []int) {
	return file_src_pbs_consultantpb_consultant_proto_rawDescGZIP(), []int{3}
}

type FindAllConsultantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consultant []*Consultant `protobuf:"bytes,1,rep,name=consultant,proto3" json:"consultant,omitempty"`
}

func (x *FindAllConsultantsResponse) Reset() {
	*x = FindAllConsultantsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllConsultantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllConsultantsResponse) ProtoMessage() {}

func (x *FindAllConsultantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_pbs_consultantpb_consultant_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllConsultantsResponse.ProtoReflect.Descriptor instead.
func (*FindAllConsultantsResponse) Descriptor() ([]byte, []int) {
	return file_src_pbs_consultantpb_consultant_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllConsultantsResponse) GetConsultant() []*Consultant {
	if x != nil {
		return x.Consultant
	}
	return nil
}

var File_src_pbs_consultantpb_consultant_proto protoreflect.FileDescriptor

var file_src_pbs_consultantpb_consultant_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c,
	0x74, 0x61, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74,
	0x61, 0x6e, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x32, 0xd5, 0x01, 0x0a, 0x11, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x59, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e,
	0x74, 0x12, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e,
	0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x12, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x73,
	0x12, 0x25, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c,
	0x74, 0x61, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1c, 0x5a, 0x0d, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x6e, 0x74,
	0x70, 0x62, 0xaa, 0x02, 0x0a, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_pbs_consultantpb_consultant_proto_rawDescOnce sync.Once
	file_src_pbs_consultantpb_consultant_proto_rawDescData = file_src_pbs_consultantpb_consultant_proto_rawDesc
)

func file_src_pbs_consultantpb_consultant_proto_rawDescGZIP() []byte {
	file_src_pbs_consultantpb_consultant_proto_rawDescOnce.Do(func() {
		file_src_pbs_consultantpb_consultant_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_pbs_consultantpb_consultant_proto_rawDescData)
	})
	return file_src_pbs_consultantpb_consultant_proto_rawDescData
}

var file_src_pbs_consultantpb_consultant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_pbs_consultantpb_consultant_proto_goTypes = []interface{}{
	(*Consultant)(nil),                 // 0: consultant.Consultant
	(*FindConsultantRequest)(nil),      // 1: consultant.FindConsultantRequest
	(*FindConsultantResponse)(nil),     // 2: consultant.FindConsultantResponse
	(*FindAllConsultantsRequest)(nil),  // 3: consultant.FindAllConsultantsRequest
	(*FindAllConsultantsResponse)(nil), // 4: consultant.FindAllConsultantsResponse
}
var file_src_pbs_consultantpb_consultant_proto_depIdxs = []int32{
	0, // 0: consultant.FindConsultantResponse.consultant:type_name -> consultant.Consultant
	0, // 1: consultant.FindAllConsultantsResponse.consultant:type_name -> consultant.Consultant
	1, // 2: consultant.ConsultantService.FindConsultant:input_type -> consultant.FindConsultantRequest
	3, // 3: consultant.ConsultantService.FindAllConsultants:input_type -> consultant.FindAllConsultantsRequest
	2, // 4: consultant.ConsultantService.FindConsultant:output_type -> consultant.FindConsultantResponse
	4, // 5: consultant.ConsultantService.FindAllConsultants:output_type -> consultant.FindAllConsultantsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_pbs_consultantpb_consultant_proto_init() }
func file_src_pbs_consultantpb_consultant_proto_init() {
	if File_src_pbs_consultantpb_consultant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_pbs_consultantpb_consultant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consultant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_consultantpb_consultant_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindConsultantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_consultantpb_consultant_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindConsultantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_consultantpb_consultant_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllConsultantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pbs_consultantpb_consultant_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllConsultantsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_pbs_consultantpb_consultant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_pbs_consultantpb_consultant_proto_goTypes,
		DependencyIndexes: file_src_pbs_consultantpb_consultant_proto_depIdxs,
		MessageInfos:      file_src_pbs_consultantpb_consultant_proto_msgTypes,
	}.Build()
	File_src_pbs_consultantpb_consultant_proto = out.File
	file_src_pbs_consultantpb_consultant_proto_rawDesc = nil
	file_src_pbs_consultantpb_consultant_proto_goTypes = nil
	file_src_pbs_consultantpb_consultant_proto_depIdxs = nil
}
